version: '2.1'

services:
  geoip-api:
    image: divadsn/geoip-api:latest

    restart: always
    depends_on:
      - geoip-update
    ports:
      - 8069:8069/tcp
    volumes:
      - ./data/GeoIP:/usr/share/GeoIP
      - ./config.py:/src/config.py

  geoip-update:
    image: wuakitv/geoipupdate:latest
    command: /etc/conf/GeoIP.conf

    restart: always
    volumes:
      - ./data/GeoIP:/geodata
      - ./data/GeoIP.conf:/etc/conf/GeoIP.conf