version: "3.8"
services:
  api:
    build: .
    restart: always
    depends_on:
      - redis
    environment:
      - WEB_CONCURRENCY=${WEB_CONCURRENCY}
      - FORWARDED_ALLOW_IPS=172.16.23.1
      - REDIS_URL=redis://redis:6379/
      - DEFAULT_LANGUAGE=${DEFAULT_LANGUAGE}
      - INCLUDE_ASN=${INCLUDE_ASN}
    ports:
      - 8069:8069/tcp
    volumes:
      - ./data:/usr/share/GeoIP
    networks:
      default:
        ipv4_address: 172.16.23.2
        aliases:
          - api
  redis:
    image: redis:6.0.7-alpine
    restart: always
    networks:
      default:
        ipv4_address: 172.16.23.3
        aliases:
          - redis
  update:
    image: tkrs/maxmind-geoipupdate:latest
    restart: always
    environment:
      - ACCOUNT_ID=${ACCOUNT_ID}
      - LICENSE_KEY=${LICENSE_KEY}
      - EDITION_IDS=GeoLite2-ASN GeoLite2-City GeoLite2-Country
    volumes:
      - ./data:/usr/share/GeoIP
    networks:
      default:
        ipv4_address: 172.16.23.4
        aliases:
          - update

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.23.0/24
